# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:

  mysql:
    image: mariadb:latest
    volumes:
      - php2_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: php2
      MYSQL_USER: php2
      MYSQL_DATABASE: php2

volumes:
  php2_mysql_data:
